using System.Text.RegularExpressions;

namespace Sample
{
    // This class is used to validate that Minicover can instrument assemblies containing code generated by a source generator.
    public static partial class ClassWithGeneratedRegex
    {
        [GeneratedRegex($@"^[^@\s]+@[^@\s]+\.[^@\s]+$", RegexOptions.IgnoreCase, "en-US")]
        private static partial Regex EmailRegex();

    }
}
