using System.Collections.Generic;
using System.Linq;
using Mono.Cecil;
using Mono.Cecil.Cil;

namespace MiniCover.Extensions
{
    public static class TypeDefinitionExtensions
    {
        public static IEnumerable<string> GetAllDocuments(this TypeDefinition typeDefinition)
        {
            return typeDefinition.GetAllMethods()
                .SelectMany(m => m.GetAllDocuments())
                .Distinct();
        }

        public static IEnumerable<MethodDefinition> GetAllMethods(this TypeDefinition typeDefinition)
        {
            if (typeDefinition.FullName == "<Module>" || typeDefinition.FullName == "AutoGeneratedProgram")
                yield break;

            foreach (var method in typeDefinition.Methods.Where(m => m.HasBody && m.DebugInformation.HasSequencePoints))
                yield return method;

            foreach (var subType in typeDefinition.NestedTypes)
            {
                foreach (var method in GetAllMethods(subType))
                    yield return method;
            }
        }

        public static bool IsCompilerGenerated(this TypeDefinition typeDefinition)
        {
            return typeDefinition.HasCompilerGeneratedAttribute()
                || (typeDefinition.DeclaringType?.IsCompilerGenerated() ?? false);
        }

        public static bool IsExcludedFromCodeCoverage(this TypeDefinition typeDefinition)
        {
            if (typeDefinition.HasExcludeFromCodeCoverageAttribute())
                return true;

            if (typeDefinition.DeclaringType != null)
                return typeDefinition.DeclaringType.IsExcludedFromCodeCoverage();

            return typeDefinition.Module.IsExcludedFromCodeCoverage();
        }
    }
}
