name: CI
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build
        run: ./build.sh
        shell: bash
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Build Sample
        run: ./build-sample.sh
        shell: bash

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          format: markdown
          output: both

      - name: Publish coverage summary
        if: matrix.os == 'ubuntu-latest'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: cobertura.xml

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Pack
        run: |
          export Version=${GITHUB_REF:11}
          echo Version: $Version
          dotnet pack -c Release -o nupkg

      - name: Push to NuGet Feed
        run: dotnet nuget push "nupkg/*.nupkg" --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
